### ISSUE TITLE
IPP/CUPS support not working

### ISSUE THREAD

**Issue by andypiper** [NaitLee/Cat-Printer#25]
When I have the server running, I can point the macOS printer utility at http://127.0.0.1:8095 and the printer gets added, but when I send a file to the printer nothing is printed and the file vanishes. I'm not sure how to debug this as there's no output from the server console.

**Comment by NaitLee** [comment]
First is didn't filter devices. Another matter of MacOS is printer BLE MAC address won't work as it's different, so you can:
- Only specify printer name
- use shorter scan time (1 or 2 seconds are enough)

You could know more about mac & ble at [bleak doc](https://bleak.readthedocs.io/en/latest/backends/macos.html)
