### ISSUE TITLE
i18n.py language detection error

### ISSUE THREAD

**Issue by Wang-Yue** [NaitLee/Cat-Printer#38]
Here you have `    self.lang = lang or locale.getdefaultlocale()[0].replace('_', '-')`

On my machine

```
>>> locale.getdefaultlocale()
(None, 'UTF-8')
```

So gives an error `AttributeError: 'NoneType' object has no attribute 'replace'`

**Comment by NaitLee** [comment]
Got it.

Thoughts about what (function call) to fallback next? Or just to English?

**Comment by Wang-Yue** [comment]
if user's locale is empty, probably fallback to en-US is the best solution

**Comment by NaitLee** [comment]
It should be fixed by 70cdd84359b12d1ef8d13cd52a3e3caa21a91e44.
