### ISSUE TITLE
GB03 darkness virtually unaffected in server mode

### ISSUE THREAD

**Issue by parkerlreed** [NaitLee/Cat-Printer#42]
Image examples. The last image is the same settings as the next to last but with quality all the way down and then all the way up. It slightly changes the sound but not the output. 

Default Android application (iPrint) darkens as expected so the hardware is fine. 

Using the python server on Arch Linux. 

![20220921_170617](https://user-images.githubusercontent.com/841440/191611118-693c3fa7-08d1-4606-990a-3a4bd74d36f9.jpg)
![20220921_170641](https://user-images.githubusercontent.com/841440/191611125-7d5ed995-67bc-420a-8584-ae7dcf879b6d.jpg)
![20220921_170723](https://user-images.githubusercontent.com/841440/191611133-b11e258b-1cf0-44c4-85c7-2b2b582aa4b8.jpg)
![20220921_170845](https://user-images.githubusercontent.com/841440/191611136-2c60999c-6dc7-4394-8611-a5dbd0e4b859.jpg)

**Comment by parkerlreed** [comment]
If I print from command line it's perfect...

```
(64)(deck@steamdeck Cat-Printer)$ python printer.py -c image ~/Downloads/Tux.png 
Cat Printer
Connecting
Finished
Disconnecting from printer
```

**Comment by parkerlreed** [comment]
Think I narrowed this down. There is no restriction to the "energy" value when setting is via "Strength" slider in the web interface.

If you move off of the default (like drag it higher) it caps out at 256 which is an invalid value for the printer, this printing everything very light. I set it back to 64 in config.json and didn't touch "Strength" slider and it printed fine.

**Comment by parkerlreed** [comment]
From index.html might make more sense to cap it at the max of 96 for text

```
                        <label class="label-span-input" data-hide-as="print">
                            <span data-i18n="strength-">Strength:</span>
                            <input type="range" min="0" max="256" value="64" step="16" name="energy" data-key data-default />
```

**Comment by NaitLee** [comment]
I remember the last change to `server.py`  changed default settings from 0.2 to an other value, for being really an integer -- but didn't change the "factor".
So it's possibly that, bigger value (> 96?) being multiplied (by factor) and excessed `0xffff`, being truncated to a small value, then printed very light.
It's adviced to check `server.py` instead.

(I'll hardly have coding time from now on)

**Comment by sync1211** [comment]
I've been playing around with that setting for some time and it appears that falls back to the default value just after 208.

Can anyone confirm whether it's only limited to the GB03 or if it also affects the other models?

**Comment by NaitLee** [comment]
The newest commit have a fixing attempt to this, adjusted where those “factors” appeared (they are poorly organized before, I admit)

Please test to prove it’s working or not. Remove the config file if necessary.
(little tip: right-click on “Settings -> Exit” will prompt if you want to reset config)
