### ISSUE TITLE
Not running on MacBook M1

### ISSUE THREAD

**Issue by AndCouvel** [NaitLee/Cat-Printer#57]
I downloaded the resources and the bare version, and this is the output:

`andrescouvel@Macbook-Air-de-Andy Cat-Printer-0.6.2.0 % cd /Users/andrescouvel/Downloads/cat-printer-2 
andrescouvel@Macbook-Air-de-Andy cat-printer-2 % python3 server.py                              
Traceback (most recent call last):
  File "/Users/andrescouvel/Downloads/cat-printer-2/server.py", line 22, in <module>
    from printer import PrinterDriver, PrinterError, i18n, info
  File "/Users/andrescouvel/Downloads/cat-printer-2/printer.py", line 48, in <module>
    i18n = I18nLib(path).translate
           ^^^^^^^^^^^^^
  File "/Users/andrescouvel/Downloads/cat-printer-2/printer_lib/i18n.py", line 23, in __init__
    self.lang = lang or (locale.getdefaultlocale()[0] or fallback).replace('_', '-')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
andrescouvel@Macbook-Air-de-Andy cat-printer-2 % `

Python 3.11.2

**Comment by NaitLee** [comment]
I feel it’s #38 revived, or at least something similar.

I’d try to look into it when I have some time.

**Comment by NaitLee** [comment]
So that I did an incomplete fix to #38. I tried to really fix it in the newest commit.

I can’t determine what time to release a new version, but you can always clone this repository and use the newest source code as you like :)

**Comment by NaitLee** [comment]
There’s a new version with fix attempt to this. Waiting for you to try it :)

**Comment by jedahan** [comment]
I was able to get python server.py running on my M1 fine with latest main

**Comment by krim404** [comment]
this can be closed as it works perfectly fine with M1, even cups printing.

**Comment by NaitLee** [comment]
ok, closing this one
