### ISSUE TITLE
MX06 can't discover device

### ISSUE THREAD

**Issue by pentirecords** [NaitLee/Cat-Printer#88]
Not sure if im doing something wrong but i have been trying to connect this MX06 printer with the latest main Cat-Printer on localhost which seems to be working normally besides the fact that i cant find my MX06 no matter how much i scan..

And also tried the https://print.unseen-site.fun/ (kitty printer) but that also can't find my MX06...

I use a Bluetooth adapter for my windows 11 pc

If anyone has any suggestions as to why i cant see the mx06 anywhere that would be awesome since i really like this app but unfortunately i cant even connect to my printer lmao, thanks for making it anyway

**Comment by NaitLee** [comment]
You may try kitty-printer on other devices (like your mobile phone or your friends’ PC), see if they can discover your MX06.

Adapter, OS, and/or PC all can be problematic, we just need to find the problem.

**Comment by strickinato** [comment]
@pentirecords - any luck?

I also have an MX06 that is not connecting.

**Comment by Urufusan** [comment]
Mind testing on a Linux distro (like Ubuntu)?

**Comment by pentirecords** [comment]
For me personally the problem was on my end since i just got a laptop yesterday and tried again on that one with just the kittyprinter web version and that one worked perfectly!
I assume its just that my desktops bluetooth adapter might not be BLE compatible or something
